services:
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:latest
    environment:
      - TZ=Europe/Rome
    volumes:
      - ./zigbee2mqtt/zigbee2mqtt.yaml:/app/data/configuration.yaml
      - ./zigbee2mqtt/external:/app/data/external
    #   - /run/udev:/run/udev:ro
    devices:
      - /dev/ttyACM1:/dev/ttyACM1
    # privileged: true
    # restart: unless-stopped
    ports:
      - 8099:8080
    # group_add:
    #   - dialout
    # user: 1000:1000

  mqtt:
    image: eclipse-mosquitto:2.0
    # restart: unless-stopped
    volumes:
      - "./runtime/mosquitto-data:/mosquitto"
    ports:
      - "1883:1883"
      - "9001:9001"
    command: "mosquitto -c /mosquitto-no-auth.conf"

  homeassistant:
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /PATH_TO_YOUR_CONFIG:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    # restart: unless-stopped
    # privileged: true
    network_mode: host
    ports:
      - 8123:8123
