# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  start:
    cmds:
      - mkdir -p runtime
      - touch runtime/devices.yaml
      - docker compose up zigbee2mqtt mqtt

  cli:
    cmds:
      - |
        docker run -it --rm efrecon/mqtt-client sub \
        -h 127.0.0.1 \
        --insecure \
        -t "#" \
        -v
