# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

dotenv: [".env"]

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  target:
    cmds:
      - idf.py set-target esp32c6
    sources:
      - sdkconfig.defaults
    generates:
      - sdkconfig

  build:
    deps: [target]
    cmds:
      - idf.py build
  
  rebuild:
    cmds:
      - rm -f sdkconfig
      - task: build

  flash:
    deps: [target]
    cmds:
      - idf.py -p ${SERIAL_PORT} flash monitor
  
  monitor:
    deps: [target]
    cmds:
      - idf.py -p ${SERIAL_PORT} monitor

  erase:
    cmds:
      - idf.py -p ${SERIAL_PORT} erase-flash
