homeassistant: true
frontend: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mqtt
serial:
  port: /dev/ttyACM0
advanced:
  pan_id: 6755
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
  last_seen: ISO_8601
  log_output:
    - console
device_options:
  legacy: false
devices: devices.yaml
external_converters:
  - external/galileo-sensor.js
  - external/galileo-temp.js
permit_join: false
log_level: debug
availability: false
groups:
  '1':
    friendly_name: all
    devices:
      - 0x543204fffe0b483c/13
