homeassistant: true
frontend: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mqtt
serial:
  port: /dev/ttyACM0
advanced:
  pan_id: 6755
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
  log_level: debug
device_options:
  legacy: false
devices: devices.yaml
external_converters:
  - external/galileo-sensor.js
  - external/galileo-temp.js
permit_join: false
log_level: debug
availability:
  active:
    timeout: 1
  passive:
    timeout: 1
